# Generated by Django 4.2.6 on 2023-10-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_displayusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayUserName',
        ),
    ]
